name: CI

on:
  pull_request:
    branches: ['**']
  push:
    branches: [main]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      MISE_EXPERIMENTAL: '1'
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Run CI
        run: mise run '//:ci'
